import { test } from "node:test";
import assert from "node:assert/strict";
import { parseManifest, serializeManifest, ManifestParseError } from "./manifest";

// A real `rag-cli answer batch --build` manifest: the generated header comment,
// a block-list knowledge_bases, and a `source` field on every question
// (rfp.Manifest shape, written by yaml.v3 with 2-space indent). The CLI reader
// (chat.LoadBatchManifest) ignores `source`, so the UI parser must accept it
// rather than reject the manifest the CLI itself emits.
const CLI_BUILD_MANIFEST = `# Generated by rag-cli answer batch --build on 2026-04-29 10:00:00 UTC
version: "1.0"
knowledge_bases:
  - vendor-docs
  - policies
questions:
  - id: "1"
    question: What is your data retention policy?
    source: Security
  - id: "2"
    question: "Do you support SSO: SAML or OIDC?"
    source: Security
  - id: "3"
    question: Describe your incident response process.
    source: Operations
`;

test("parses a CLI --build manifest that carries a source field per question", () => {
  const m = parseManifest(CLI_BUILD_MANIFEST);
  assert.equal(m.version, "1.0");
  assert.deepEqual(m.knowledge_bases, ["vendor-docs", "policies"]);
  assert.equal(m.questions.length, 3);
  // source is accepted and retained (regression: it used to throw
  // "unexpected field source in question").
  assert.equal(m.questions[0].source, "Security");
  assert.equal(m.questions[2].source, "Operations");
  // A colon inside a quoted question value survives.
  assert.equal(m.questions[1].question, "Do you support SSO: SAML or OIDC?");
});

test("round-trips a CLI --build manifest unchanged (source + KBs preserved)", () => {
  const parsed = parseManifest(CLI_BUILD_MANIFEST);
  const reparsed = parseManifest(serializeManifest(parsed));
  assert.deepEqual(reparsed, parsed);
  assert.equal(reparsed.questions[2].source, "Operations");
});

test("ignores unknown question fields, matching the CLI's lenient decoder", () => {
  const m = parseManifest(`version: "1.0"
questions:
  - id: "1"
    question: A question?
    future_field: something the CLI does not know
`);
  assert.equal(m.questions.length, 1);
  assert.equal(m.questions[0].question, "A question?");
});

test("accepts inline and block-list knowledge_bases forms", () => {
  const inline = parseManifest(`version: "1.0"
knowledge_bases: [a, b]
questions:
  - question: Q?
`);
  assert.deepEqual(inline.knowledge_bases, ["a", "b"]);
});

test("still rejects a manifest with no questions", () => {
  assert.throws(() => parseManifest(`version: "1.0"\n`), ManifestParseError);
});

test("still rejects a question with an empty question field", () => {
  assert.throws(
    () =>
      parseManifest(`version: "1.0"
questions:
  - id: "1"
    source: Security
`),
    ManifestParseError
  );
});
