name: rag
base: core24
version: &snap-version "v0.0.1"
summary: DeepSeek R1
description: |
  This snap configures OpenSearch models, pipelines, and indexes 
  for a CLI RAG application.

grade: devel
confinement: strict
confinement: strict

assumes:
  - snapd2.68 # for components support

compression: lzo

environment:
  # Workaround until it gets set by snapd
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION

plugs:
  intel-npu:
    interface: custom-device
    custom-device: intel-npu-device
  npu-libs:
    interface: content
    content: npu-libs-2404
    target: $SNAP/npu-libs

layout: {}

parts:
  app-scripts:
    source: apps
    plugin: dump
    organize:
      "*": bin/

  system-utilities:
    plugin: nil
    stage-packages:
      - pciutils

  go-clis:
    plugin: go
    build-snaps:
      - go/1.24/stable
    source: .
    source-type: local

  common-runtime-dependencies:
    plugin: nil
    stage-packages:
      - wget # model init
      - jq # install hook
    stage-snaps:
      - yq # install hook

apps:
  rag:
    command: bin/rag
    completer: bin/completion.bash
    plugs:
      # To access server over network socket
      - network
    environment:
      CHAT: $SNAP/bin/chat.sh
      KNOWLEDGE: $SNAP/bin/knowledge.sh