name: rag
base: core24
version: &snap-version "v0.0.1"
summary: RAG CLI application
description: |
  This snap configures OpenSearch snap models, pipelines, and indexes 
  for a RAG implementation connected to the Inference snap.

grade: devel
confinement: strict

assumes:
  - snapd2.68 # for components support

compression: lzo

environment:
  # Workaround until it gets set by snapd
  SNAP_COMPONENTS: /snap/$SNAP_INSTANCE_NAME/components/$SNAP_REVISION

parts:
  app-scripts:
    source: apps
    plugin: dump
    organize:
      "*": bin/

  system-utilities:
    plugin: nil
    stage-packages:
      - pciutils

  go-cli:
    plugin: go
    build-snaps:
      - go/1.24/stable
    source: .
    source-type: local

  common-runtime-dependencies:
    plugin: nil
    stage-packages:
      - wget # model init
      - jq # install hook
    stage-snaps:
      - yq # install hook

apps:
  rag:
    command: bin/cli
    completer: bin/completion.bash
    plugs:
      # To access server over network socket
      - network
    environment:
      RAG: $SNAP/bin/rag.sh